### ISSUE TITLE
Using '---' as value gives an error

### ISSUE THREAD

**Issue by ws-way** [TomWright/dasel#101]
Hello,

With 1.13.3 I do a

echo '' | dasel put string -p yaml 'extraEnv.[0].name' 'KEYCLOAK_STATISTICS' | \
          dasel put string -p yaml 'extraEnv.[0].value' 'ALL' | \
          dasel put string -p yaml 'extraEnv.[1].name' 'KEYCLOAK_USER' | \
          dasel put string -p yaml 'extraEnv.[1].value' 'admin' | \
          dasel put string -p yaml 'extraEnv.[2].name' 'KEYCLOAK_PASSWORD' | \
          dasel put string -p yaml 'extraEnv.[2].value' '---keycloak-password---'

which gives a 'Error: bad flag syntax: ---keycloak-password---'.

Is there anyway I can start a string with '---' ?

Thanks.

**Comment by TomWright** [comment]
I've found that you're facing this issue because of the flag parser being used: https://github.com/spf13/pflag/blob/85dd5c8bc61cfa382fecd072378089d4e856579d/flag.go#L962

I can look into a workaround/fix for this but since it's outside of my control I can suggest an alternative approach using `put document` for the meantime:

```bash
echo 'extraEnv:
- name: KEYCLOAK_STATISTICS
  value: ALL
- name: KEYCLOAK_USER
  value: admin' | ./dasel put document -p yaml 'extraEnv.[2]' -d yaml '
name: KEYCLOAK_PASSWORD
password: ---keycloak-password---
'
```

**Comment by ws-way** [comment]
Ok, thanks, this will do
