### ISSUE TITLE
dasel formats the original file in a different format

### ISSUE THREAD

**Issue by dcompoze** [TomWright/dasel#108]
**Version**

Current master

**Issue**

I have a `Cargo.toml` file with the following contents:

```toml
[profile.dev]
  debug = true
  opt-level = 0

[profile.release]
  debug = false
  opt-level = 3
```

Whenever I use `dasel` to update a value inside the file, it changes the formatting of the file to a different style, in this case the above becomes:

```toml

[profile]

  [profile.dev]
    debug = true
    opt-level = 0

  [profile.release]
    debug = false
    opt-level = 3
```

It also adds a lot of whitespace between sections and and the top of the file

Ideally I would expect the file not to be automatically re-formatted in a different style as long as it's a valid TOML/JSON/YAML format.

**Comment by TomWright** [comment]
Hi @dcompoze,

[This is documented in the readme](https://github.com/TomWright/dasel#preserved-formatting-and-ordering).

This is an unfortunate side-effect due to the way that dasel actually works with data in that it:
1. Unmarshals text into a `map[string]interface{}`
2. Performs actions on the map
3. Marshals the map back into text

I don't see any real way around this since dasel is relying on external packages for the marshal/unmarshal functionality.
