### ISSUE TITLE
Json to Toml transforms int to float

### ISSUE THREAD

**Issue by MattKetmo** [TomWright/dasel#208]
When transform from JSON to TOML I noticed all my integers are converted to float.
Other formats work correctly.

It's pretty easy to reproduce:

```
$ echo '{"foobar": 42}' | dasel -r json -w toml
foobar = 42.0

$ echo '{"foobar": 42}' | dasel -r json -w yaml
foobar: 42

$ echo '{"foobar": 42}' | dasel -r json -w json
{
  "foobar": 42
}
```

What I'm expecting for the first command:
```
$ echo '{"foobar": 42}' | dasel -r json -w toml
foobar = 42
```

I'm using dasel version `v1.23.0`

Thanks.

**Comment by TomWright** [comment]
The issue here is not that the TOML parser is doing something wrong, it's that the JSON parser is returning a float: https://pkg.go.dev/encoding/json#Unmarshal

> To unmarshal JSON into an interface value, Unmarshal stores one of these in the interface value:
> 
> bool, for JSON booleans
> float64, for JSON numbers
> string, for JSON strings
> []interface{}, for JSON arrays
> map[string]interface{}, for JSON objects
> nil for JSON null

```bash
$ echo '{"a":42}' | dasel -r json -w plain '.a.[@]'
float
```

I need to think about whether this is something we should be changing on this end. I think I've seen somewhere that this is actually correct according to the JSON spec, but take that with a pinch of salt.

**Comment by MattKetmo** [comment]
Indeed, I understand better: json & yaml writter are stripping the .0 of the float
```
$ echo '{"foobar": 42.0}' | dasel -r json -w yaml
foobar: 42
```

Which means one alternative to my issue would be to convert to yaml first and then toml :)
```
$ echo '{"foobar": 42}' | dasel -r json -w yaml | dasel -r yaml -w toml
foobar = 42
```
