### ISSUE TITLE
support for a validation command

### ISSUE THREAD

**Issue by foolioo** [TomWright/dasel#219]
**Is your feature request related to a problem? Please describe.**
**dasel is awesome!**
since i love it too much and although dasel is not a validator, i do use it as such.

**Describe the solution you'd like**
i would love to see an option to provide dasel with a list of files (of any supported types), and have dasel report whether any error is found. e.g.

```shell
$ dasel validate dir/foo.json dir/foo.yaml
pass dir/foo.json
fail dir/foo.yaml
$ echo $?
1

$ dasel validate 'dir/**/*.{json,yaml}'
pass dir/foo.json
fail dir/foo.yaml
$ echo $?
1
```

**Describe alternatives you've considered**
wrapping dasel with a helper
```shell
find . -type f -name '*.yaml' -o -name '*.json' | while read f; do dasel -f $f; done
```

**Comment by TomWright** [comment]
This doesn't seem to hard (famous last words). I'll keep it in mind!

**Comment by foolioo** [comment]
@TomWright: in the same note, it beats jq/yq/xq when looking at the validation. when jq/yq/xq fail to parse, dasel succeeds.

again, thank you for dasel.

**Comment by TomWright** [comment]
> @TomWright Would you accept a contribution with this feature?

Yes of course. I'll accept contributions in any area

**Comment by TomWright** [comment]
I'll get a PR up for this as soon as I can. I haven't had much time in-front on the computer this week

**Comment by TomWright** [comment]
My current thoughts are that:
- `dasel validate` supports 0 or more arguments.
- If 1 or more arguments are given each argument will be parsed using a similar syntax to `find` on linux.
- If 0 arguments are given, dasel will look to `stdin` for some raw content. If this is the case dasel will expect either a `-r` or `-p` flag to determine the expected format.
- If read from `stdin` dasel will output `pass` or `fail` along with a `0` or `1` exit code.
- If files were given, dasel will output `pass $file` or `fail $file` along with a `0` or `1` exit code. `0` is output if all files passed otherwise `1`.
- If anything failed, output is written to `stderr`, otherwise `stdout` is used.

```bash
$ dasel validate x.json y.yaml z.toml
pass x.json
fail y.yaml
pass z.toml
$ echo $?
1
```

```bash
$ dasel validate x.json z.toml
pass x.json
pass z.toml
$ echo $?
0
```

```bash
$ echo '{' | dasel validate -r json
fail
$ echo $?
1
```

```bash
$ echo '{"name":"Tom"}' | dasel validate -r json
pass
$ echo $?
0
```

I may include the actual error after `fail $file` and include a `--plain` flag to have the errors stripped from output.

**Comment by TomWright** [comment]
My initial PR for this is here: https://github.com/TomWright/dasel/pull/231

The current usage is that `dasel validate` accepts a list of files in the arguments and will output one line for each file:

```
pass ./../../tests/assets/example.json
pass ./../../tests/assets/example.yaml
fail ./../../tests/assets/broken.json could not load input: could not unmarshal data: invalid character '}' after array element
fail ./../../tests/assets/broken.xml could not load input: could not unmarshal data: xml.Decoder.Token() - XML syntax error on line 1: element <a> closed by </b>
```

The error after the filename can be toggled off with `--include-error=false`.

**Comment by TomWright** [comment]
Note that it also supports glob patterns in place of a filename:

```bash
$ dasel validate ./../../tests/assets/*.json
pass ../../tests/assets/example.json
fail ../../tests/assets/broken.json could not load input: could not unmarshal data: invalid character '}' after array element
```

**Comment by TomWright** [comment]
I have now updated the docs: https://daseldocs.tomwright.me/usage/validate

**Comment by TomWright** [comment]
This will be included in the next release.
