### ISSUE TITLE
Put documentation, shows a option "--plain" which isn't available 

### ISSUE THREAD

**Issue by tobiashochguertel** [TomWright/dasel#254]
When I modify with dasel my pom.xml files, they get complete reformated. I checked the docs, and found out that there is a option "--plain" described which stops reformating the document. I tried it out with the current version (v1.27.3) of dasel, but dasel doesn't offer this option.

Can we get this feature or remove the information from the docs? I would prefer to get this feature 🥇 .

**Comment by TomWright** [comment]
Hey @tobiashochguertel,

As specified in the docs:
>By default, dasel formats the output using the specified parser. If this flag is used no formatting occurs and the results output as a string.

The `--plain` flag is simply an alias for `-w -`.

Dasel uses external parsers/encoders to read/write documents so cannot promise no formatting changes in the documents.

The `--plain` flag is more useful when selecting data rather than writing it as in this case.
