### ISSUE TITLE
`dasel put --type string` not working when converting to yaml

### ISSUE THREAD

**Issue by DeluxeOwl** [TomWright/dasel#344]
**Describe the bug**
When I'm doing this:
```sh
dasel put --type string --file values.dev.yaml --selector "annotations.previousShortSHA" -v 1615
```

the value comes out as a number
```yaml
annotations:
    branch: main
    previousShortSHA: 1615
```

**Expected behavior**
`previousShortSHA` should be `"1615"`

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] `ubuntu, manjaro`
- Version [e.g. 22] (`dasel --version`): `2.3.4`

**Additional context**
I'm using ArgoCD for kubernetes and I was bitten by this when doing the following:
```sh
dasel put -t string --file "values.dev.yaml" --selector "annotations.previousShortSHA" -v "$(git rev-parse --short HEAD)"
```

and it so happened that `"$(git rev-parse --short HEAD)"` returned a **number**:
![image](https://github.com/TomWright/dasel/assets/54327698/50f0e087-ede0-45eb-a4d9-9810cbfd57a9)

and ArgoCD threw an error because it expected a string

**Comment by Argelbargel** [comment]
Hi. I've got a similar problem. I'm modifying an existing YAML file adding some keys. After writing it out as YAML empty string are converted to nil/null instead of empty strings. So this:

empty_value: ""

is converted to

empty_value:

which ist okay most of the time - except when the code reading the YAML checks explicitly for the empty string. So keeping the type/quoting empty values would be a great option

**Comment by TomWright** [comment]
I've been on holiday but will try to add the flag mentioned above once I've caught up with work

**Comment by TomWright** [comment]
```
tom ~ $ dasel -v
dasel version 2.3.5
tom ~ $ echo 'annotations:
  previousShortSHA: old' | dasel put -r yaml -t string -v '1615' 'annotations.previousShortSHA'
annotations:
    previousShortSHA: "1615"
```
